webamcr/detectors/urls.py
from django.urls import path

from . import views

app_name = 'pas'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('create/<str:ident_cely>/', views.create, name="detail"),
    path('history/<str:ident_cely>/', views.historyDetectorsList, name="detectors_history"),
    path('choose/', views.choose, name="choose"),
    path('myfinds/', views.my_detectors, name='moje_list'),
    path('cooperate/', views.cooperate, name="cooperate"),
    path('cooperate/update/<int:pk>/', views.updateCooperation, name="cooparate_update"),
    path('cooperate/create/', views.createCooperation, name="cooparate_create"),
    path('cooperate/delete/<int:pk>/', views.deleteCooperation, name="cooparate_delete"),
    path('cooperate/history/<int:pk>/', views.historyCooperationList, name='cooperate_history'),
    path('confirm/', views.confirm, name="confirm"),  # list findings to be confirmed
    path('archive/', views.archive, name="archive"),  # list findings to be archived
    path('return/<str:ident_cely>/', views.return_finding, name="return_finding"),

    path('file/upload/<int:projectId>/<str:findingIdentCely>/', views.upload, name="upload"),
]

webamcr/webamcr/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from . import views
from documents.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('', views.home, name='home'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
	path('documents/', include('documents.urls')),
    path('pas/', include('detectors.urls')),
    path('django-rq/', include('django_rq.urls')),
    path('admin/', admin.site.urls),
    path('file/delete/<int:fileId>/', views.delete, name='delete_file'),
    path('user/', include('amcrusers.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

handler403 = 'webamcr.views.err_sid'

urlpatterns += staticfiles_urlpatterns()

webamcr/detectors/models.py
from django.db import models

from .constants import DetectorConstants as c
from django.conf import settings

class HeslarPristupnost(models.Model):
    nazev = models.CharField(max_length=1)
    vyznam = models.TextField()
    validated = models.SmallIntegerField()
    en = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'heslar_pristupnost'


class HeslarTypOrganizace(models.Model):
    nazev = models.TextField(blank=True, null=True)
    validated = models.SmallIntegerField()
    poradi = models.SmallIntegerField()

    class Meta:
        managed = False
        db_table = 'heslar_typ_organizace'


class Atree(models.Model):
    item_type = models.IntegerField(blank=True, null=True)
    parent_id = models.IntegerField(blank=True, null=True)
    owner_id = models.IntegerField(blank=True, null=True)
    ctime = models.DateTimeField(blank=True, null=True)
    position = models.IntegerField(blank=True, null=True)
    caption = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'atree'


class Organizace(models.Model):
    id = models.IntegerField(primary_key=True)
    nazev = models.TextField(blank=True, null=True)
    nazev_zkraceny = models.TextField(blank=True, null=True)
    zkratka = models.TextField(blank=True, null=True)
    typ_organizace = models.ForeignKey(HeslarTypOrganizace, models.DO_NOTHING, db_column='typ_organizace', blank=True, null=True)
    oao = models.BooleanField(blank=True, null=True)
    published_accessibility = models.ForeignKey(HeslarPristupnost, models.DO_NOTHING, db_column='published_accessibility')
    months_to_publication = models.IntegerField()
    en = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'organizace'


class UserStorage(models.Model):
    id = models.OneToOneField(Atree, models.DO_NOTHING, db_column='id', primary_key=True)
    jmeno = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    pasw = models.TextField(blank=True, null=True)
    auth_level = models.IntegerField(blank=True, null=True)
    telefon = models.TextField(blank=True, null=True)
    # ID je stejne jako PK v tabulce Organizace proto zde odpojuji relaci na Atree
    organizace = models.ForeignKey(Organizace, models.DO_NOTHING, related_name='user_organizace', db_column='organizace', blank=True, null=True)
    news = models.IntegerField(blank=True, null=True)
    prijmeni = models.TextField(blank=True, null=True)
    confirmation = models.TextField(blank=True, null=True)
    notifikace_nalezu = models.BooleanField()
    ident_cely = models.TextField()
    jazyk = models.CharField(max_length=15, choices=settings.LANGUAGES, null=False, default='cs')

    class Meta:
        managed = False
        db_table = 'user_storage'


class VazbaSpoluprace(models.Model):
    badatel = models.ForeignKey(UserStorage, on_delete=models.DO_NOTHING, related_name='spoluprace_badatele', db_column='badatel', blank=True, null=True)
    archeolog = models.ForeignKey(UserStorage, on_delete=models.DO_NOTHING, related_name='spoluprace_archeologove', db_column='archeolog', blank=True, null=True)
    aktivni = models.BooleanField(blank=True, null=True)
    potvrzeno = models.BooleanField(blank=True, null=True)
    datum_vytvoreni = models.IntegerField(blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'vazba_spoluprace'


class SamostatnyNalez(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True)
    inv_cislo = models.TextField(null=True)
    projekt = models.IntegerField(null=True)
    katastr = models.IntegerField(null=True)
    lokalizace = models.TextField(null=True)
    okolnosti = models.IntegerField(null=True)
    geom = models.TextField(null=True)  # This field type is a guess. There should be a GeometryField of the GeoDjango library https://docs.djangoproject.com/en/2.2/ref/contrib/gis/install/#windows
    pristupnost = models.IntegerField(null=True)
    obdobi = models.IntegerField(null=True)
    presna_datace = models.TextField(null=True)
    typ_nalezu = models.IntegerField(null=True)
    druh_nalezu = models.IntegerField(null=True)
    specifikace = models.IntegerField(null=True)
    pocet = models.IntegerField(null=True)
    poznamka = models.TextField(null=True)
    nalezce = models.ForeignKey(UserStorage, models.DO_NOTHING, db_column='nalezce',null=True)
    datum_nalezu = models.DateField(null=True)
    odpovedny_pracovnik_vlozeni = models.IntegerField(null=True)
    datum_vlozeni = models.IntegerField(null=True)
    odpovedny_pracovnik_archivace = models.IntegerField(null=True)
    datum_archivace = models.IntegerField(null=True)
    stav = models.IntegerField(null=False)
    predano = models.BooleanField(null=True)
    predano_organizace = models.IntegerField(null=True)
    poradi = models.IntegerField(null=True)
    ident_cely = models.TextField(null=True)

    class Meta:
        managed = False
        db_table = 'samostatny_nalez'


class Soubor(models.Model):
    dokument = models.IntegerField(blank=True, null=True)
    nazev = models.TextField()
    uzivatelske_oznaceni = models.TextField(blank=True, null=True)
    rozsah = models.IntegerField(blank=True, null=True)
    vlastnik = models.IntegerField()
    filepath = models.TextField(unique=True)
    mimetype = models.TextField()
    size_bytes = models.IntegerField()
    nahled = models.IntegerField(blank=True, null=True)
    vytvoreno = models.DateField(blank=True, null=True)
    projekt = models.IntegerField(blank=True, null=True)
    typ_souboru = models.TextField(blank=True, null=True)
    samostatny_nalez = models.ForeignKey(SamostatnyNalez, models.DO_NOTHING, db_column='samostatny_nalez', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'soubor'


class HistorieSpoluprace(models.Model):
    datum_zmeny = models.DateTimeField(auto_now_add=True, blank=False, null=False)
    typ_zmeny = models.IntegerField(default=0, choices=c.TYP_ZMENY_SPOLUPRACE, blank=False, null=False)
    vazba_spoluprace = models.ForeignKey(VazbaSpoluprace, on_delete=models.CASCADE, db_column='vazba_spoluprace', blank=False, null=False)
    uzivatel = models.ForeignKey(UserStorage, models.DO_NOTHING, db_column='uzivatel', blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'historie_spoluprace'


class HistorieSamNalezu(models.Model):
    datum_zmeny = models.DateTimeField(auto_now_add=True, blank=False, null=False)
    typ_zmeny = models.IntegerField(default=0, choices=c.TYPY_ZMENY_SAM_NALEZU, blank=False, null=False)
    samostatny_nalez = models.ForeignKey(SamostatnyNalez, on_delete=models.CASCADE, db_column='samostatny_nalez', blank=False, null=False)
    uzivatel = models.ForeignKey(UserStorage, models.DO_NOTHING, db_column='uzivatel', blank=False, null=False)
    duvod = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'historie_samostatny_nalez'

# ------------------ MODELY PRO PROJEKT ----------------------

class HeslarJmena(models.Model):
    jmeno = models.TextField(blank=True, null=True)
    prijmeni = models.TextField(blank=True, null=True)
    validated = models.SmallIntegerField()
    vypis = models.TextField(blank=True, null=True)
    vypis_cely = models.TextField(unique=True, blank=True, null=False)

    class Meta:
        managed = False
        db_table = 'heslar_jmena'
        unique_together = (('jmeno', 'prijmeni'),)


class HeslarKulturniPamatka(models.Model):
    nazev = models.TextField(blank=True, null=True)
    validated = models.SmallIntegerField()
    poradi = models.SmallIntegerField()

    class Meta:
        managed = False
        db_table = 'heslar_kulturni_pamatka'


class HeslarTypProjektu(models.Model):
    nazev = models.TextField(blank=True, null=True)
    validated = models.SmallIntegerField()
    poradi = models.SmallIntegerField()

    class Meta:
        managed = False
        db_table = 'heslar_typ_projektu'


class Projekt(models.Model):
    id = models.OneToOneField(Atree, models.DO_NOTHING, db_column='id', primary_key=True)
    odpovedny_pracovnik_zapisu = models.ForeignKey('UserStorage', on_delete=models.DO_NOTHING, related_name='odpovedny_pracovnici_zapisu', db_column='odpovedny_pracovnik_zapisu', blank=True, null=True)
    odpovedny_pracovnik_prihlaseni = models.ForeignKey('UserStorage', on_delete=models.DO_NOTHING, related_name='odpovedny_pracovnici_prihlaseni', db_column='odpovedny_pracovnik_prihlaseni', blank=True, null=True)
    odpovedny_pracovnik_archivace = models.ForeignKey('UserStorage', on_delete=models.DO_NOTHING, related_name='odpovedny_pracovnici_archivace', db_column='odpovedny_pracovnik_archivace', blank=True, null=True)
    stav = models.SmallIntegerField(blank=True, null=True)
    time_of_change = models.IntegerField(blank=True, null=True)
    odpovedny_pracovnik_navrhu_zruseni = models.ForeignKey('UserStorage', on_delete=models.DO_NOTHING, related_name='odpovedny_pracovnici_navrhu_zruseni', db_column='odpovedny_pracovnik_navrhu_zruseni', blank=True, null=True)
    odpovedny_pracovnik_zruseni = models.ForeignKey('UserStorage', on_delete=models.DO_NOTHING, related_name='odpovedny_pracovnici_zruseni', db_column='odpovedny_pracovnik_zruseni', blank=True, null=True)
    adresa = models.TextField(blank=True, null=True)
    dalsi_katastry = models.TextField(blank=True, null=True)
    typ_projektu = models.ForeignKey(HeslarTypProjektu, related_name='projekty_typy', on_delete=models.DO_NOTHING, db_column='typ_projektu', blank=True, null=True)
    email = models.TextField(blank=True, null=True)

webamcr/detectors/templates/components/button-group-det.html
{% load i18n %}
<style>
    .btn-det-group{
        padding: 5px 10px !important;
    }
</style>
<div class="col-12 col-xl-9 mt-2 mb-2">
    <div class="row pr-md-2">
        {% if smStav == 0 %}
        <div class="col-6 col-md-3 col-lg-2 btn-det-group">
            <button name="button_return" type="button" id="backButton" class="btn btn-amcr btn-block" onclick="goBack()">{% trans "Zpět" %}</button>
        </div>
        {% else %}
        <div class="col-6 col-md-3 col-lg-2 btn-det-group">
            <button name="button_close" type="button" id="backButton" class="btn btn-amcr btn-block closeTab">{% trans "Zavřít" %}</button>
        </div>
        {% endif %}
        {% if canEdit and ident_cely != '0' %}
        <div class="col-6 col-md-3 col-lg-2 btn-det-group">
            <button type="button" id="deleteButton" class="btn btn-amcr btn-block" data-toggle="modal" data-target="#delete_detector">
                {% trans "Smazat" %}
                </buton>
        </div>
        {% else %}
        <div class="col-6 col-md-3 col-lg-2 btn-det-group">
            <button class="btn btn-amcr btn-block disabled" readonly="true">
                {% trans "Smazat" %}
            </button>
        </div>
        {% endif %}

        {% with 'Archeolog Archivář Admin' as list_archeolog %}
        {% if userDetail.role_opravneni.role in list_archeolog %}
        {% if canConfirm or canArchive or canUnarchive %}
        <div class="col-6 col-md-3 col-lg-2 mt-sm-0 btn-det-group">
            <a class="btn btn-amcr btn-block checkchanges" href="{% url 'pas:return_finding' ident_cely %}">{% trans "Vrátit" %}</a>
        </div>
        {% else %}
        <div class="col-6 col-md-3 col-lg-2 mt-md-0 btn-det-group">
            <button class="btn btn-amcr btn-block disabled" readonly="true">
                {% trans "Vrátit" %}
            </button>
        </div>
        {% endif %}
        {% endif %}
        {% endwith %}
        <div class="col-6 col-md-3 col-lg-2 mt-md-0 btn-det-group">
            <button class="btn btn-amcr btn-block disabled" readonly="true">{% trans "Výpis" %}</button>
        </div>
    </div>
    <div class="row pr-md-2">

        {% with 'Archivář Admin' as list_archivar %}
        {% if userDetail.role_opravneni.role in list_archivar %}
        {% if canArchive  %}
        <div class="col-6 col-md-3 col-lg-2 btn-det-group">
            <button id="send_to_archive_button" type="button" class="btn btn-amcr btn-block checkchanges" data-toggle="modal" data-target="#archive_detector">
                {% trans "Archivovat" %}
            </button>
        </div>
        {% else %}
        <div class="col-6 col-md-3 col-lg-2 btn-det-group">
            <button class="btn btn-amcr btn-block disabled" readonly="true">
                {% trans "Archivovat" %}
            </button>
        </div>
        {% endif %}
        {% endif %}
        {% endwith %}

        {% if ident_cely != '0' %}
        <div class="col-6 col-md-3 col-lg-2 btn-det-group checkchanges">
            <a class="btn btn-amcr btn-block" href="{% url 'pas:detectors_history' ident_cely %}">
                {% trans "Historie nálezu" %}
            </a>
        </div>
        {% endif %}
    </div>
</div>

webamcr/detectors/templates/components/changed-form-pas-modal.html
{% load i18n %}

<!-- Changes modal -->
<div class="modal fade" id="formChangeModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans "Formulář byl editován" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>{% trans "Ve formuláři jsou neuložené změny." %}</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-amcr btn-block" href="{% url 'pas:detail' ident_cely %}">{% trans "Zahodit změny" %}</a>
        <button class="btn btn-amcr btn-block" name="button_save">{% trans "Uložit změny" %}</button>
      </div>
    </div>
  </div>
</div>

webamcr/detectors/templates/components/history_table.html
{% load i18n %}
{% load tz %}
{% get_current_language as LANGUAGE_CODE %}
<!--Table-->
<table id="history_table" data-locale="{{ LANGUAGE_CODE }}" data-toggle="table" data-toolbar="#toolbar" data-pagination="true" data-pagination-pre-text="{% trans "Předchozí" %}" data-show-pagination-switch="true" data-search="true"
    data-pagination-next-text="{% trans "Další" %}" data-show-jump-to="true" data-show-columns="true" data-show-toggle="true" data-show-export="true" data-mobile-responsive="true" data-buttons-class="amcr btn-xs"
    class="table table-hover table-borderless">
    <!--Table head-->
    <thead scope="col" class="col-documents col-detectors-head">
        <tr>
            <th data-field="datum_zmeny" data-sortable="true">{% trans "Datum změny" %}</th>
            <th data-field="typ_zmeny" data-sortable="true">{% trans "Typ změny" %}</th>
            <th data-field="uzivatel" data-sortable="true">{% trans "Uživatel" %}</th>
            <th data-field="ident" data-sortable="true">{% trans "Identifikátor" %}</th>
            <th data-field="organizace" data-sortable="true">{% trans "Organizace" %}</th>
            <th data-field="duvod" data-sortable="true">{% trans "Komentář" %}</th>
        </tr>
    </thead>
    <!--Table head-->
    <!--Table body-->
    <tbody>
        {% for s in historie %}
        <tr>
            <td>{{s.datum_zmeny|timezone:"Europe/Prague"|date:'Y-m-d H:i' }}</td>
            <td>{{s.get_typ_zmeny_display}}</td>
            <td>{{ s.uzivatel.prijmeni }}, {{s.uzivatel.jmeno}}</td>
            <td>{{ s.uzivatel.ident_cely }}</td>
            <td>{{ s.uzivatel.organizace.nazev_zkraceny }}</td>
            <td>{{s.duvod}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <!--Table body-->
</table>

webamcr/detectors/templates/components/spoluprace_table.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!--Table-->
<table id="coop_table" data-locale="{{ LANGUAGE_CODE }}" data-min-width="560" data-toggle="table" data-toolbar="#toolbar" data-pagination="true"
    data-pagination-pre-text="{% trans "Předchozí" %}" data-pagination-next-text="{% trans "Další" %}" data-show-columns="true" data-search="true"
    data-show-toggle="true" data-mobile-responsive="true" data-show-export="true" data-page-size="100" data-buttons-class="amcr btn-xs"
    class="table table-hover table-borderless">
    <!--Table head-->
    <thead scope="col" class="col-detectors-head">
        <tr>
            <th data-field="detail" data-width="50" data-halign="center" data-align="center">
                <i class="ti-new-window d-none d-sm-inline"></i>
                <span class="d-inline d-sm-none">{% trans "Detail spolupráce" %}</span>
            </th>
            <th data-field="historie" data-width="50" data-halign="center" data-align="center">
                <i class="ti-timer d-none d-sm-inline"></i>
                <span class="d-inline d-sm-none">{% trans "Historie spolupráce" %}</span>
            </th>
            <th data-field="badatel" data-sortable="true" class="table-long">{% trans "Badatel" %}</th>
            <th data-field="badatelOrganizace" data-sortable="true" data-visible="true" class="table-long">{% trans "Organizace (badatel)" %}</th>
            <th data-field="badatelEmail" data-sortable="true" data-visible="true">{% trans "Email (badatel)" %}</th>
            <th data-field="archeolog" data-sortable="true" class="table-long">{% trans "Archeolog" %}</th>
            <th data-field="archeologOrganizace" class="table-long-2" data-sortable="true" data-visible="true">{% trans "Organizace (archeolog)" %}</th>
            <th data-field="archeologEmail" data-sortable="true" data-visible="true">{% trans "Email (archeolog)" %}</th>
            <th data-field="aktivni" data-sortable="true" class="table-short">{% trans "Aktivní" %}</th>
            <th data-field="potvrzeno" data-sortable="true" class="table-short">{% trans "Potvrzeno" %}</th>
            <th data-field="potvrzeni" data-sortable="true" class="table-long">{% trans "Datum potvrzení" %}</th>
            {% if context.canDelete %}
            <th data-field="smazat" data-width="50" data-halign="center" data-align="center">
                <i class="ti-close d-none d-sm-inline"></i>
                <span class="d-inline d-sm-none">{% trans "Smazat spolupráci" %}</span>
            </th>
            {% endif %}
        </tr>
    </thead>
    <!--Table head-->
    <!--Table body-->
    <tbody>
        {% for s in context.spoluprace %}
        <tr>
            <td>
                <a class="icon-container" href="{% url 'pas:cooparate_update' s.id %}" data-toggle="tooltip" data-placement="right" title="{% trans "Detail spolupráce" %}">
                    <i class="ti-new-window"></i>
                </a>
            </td>
            <td>
                <a class="icon-container" href="{% url 'pas:cooperate_history' s.id %}" data-toggle="tooltip" data-placement="right" title="{% trans "Historie spolupráce" %}">
                    <i class="ti-timer"></i>
                </a>
            </td>
            <td>{{s.badatel}}</td>
            <td>{{s.badatel_organizace}}</td>
            <td>{{s.badatel_email}} ({{s.badatel_ident}})</td>
            <td>{{s.archeolog}}</td>
            <td>{{s.archeolog_organizace}}</td>
            <td>{{s.archeolog_email}} ({{s.archeolog_ident}})</td>
            <td>{{s.aktivni}}</td>
            <td>{{s.potvrzeno}}</td>
            <td>{{s.zmena_potvrzeni.datum_zmeny|date:'Y-m-d H:i'}}</td>
            {% if context.canDelete %}
            <td>
                <a class="icon-container" data-toggle="tooltip" data-placement="left" title="{% trans "Smazat spolupráci" %}">
                    <i class="ti-close" data-toggle="modal" data-target="#delete_cooperation-{{ s.id }}"></i>
                </a>
            </td>
                <!-- MODAL DELETE PHOTO -->
                <div class="modal fade" id="delete_cooperation-{{ s.id }}" tabindex="-1" role="dialog"
                    aria-labelledby="deleteCooperationTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="w-100 modal-title" id="deleteCooperationTitle">{% trans "Smazat spolupráci" %}</h5>
                            </div>
                            <div class="modal-body">
                                <p>{% trans "Opravdu chcete tuto spolupráci smazat?" %}</p>
                            </div>
                            <div class="modal-footer">
                                <a class="btn btn-amcr btn-block" href="" data-dismiss="modal">{% trans "Ne" %}</a>
                                <a class="btn btn-amcr btn-block" href="{% url 'pas:cooparate_delete' s.id %}">{% trans "Ano" %}</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END OF MODAL DELETE PHOTO-->
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
    <!--Table body-->
</table>


webamcr/detectors/templates/components/table.html
{% load i18n %}
<!-- Table component -->
{% get_current_language as LANGUAGE_CODE %}
<table id="detector_table" data-locale="{{ LANGUAGE_CODE }}" data-min-width="560" data-toggle="table" data-toolbar="#toolbar" data-pagination="true"
    data-show-pagination-switch="true" data-pagination-pre-text="{% trans "Předchozí" %}" data-pagination-next-text="{% trans "Další" %}" data-search="true"
    data-show-columns="true" data-show-toggle="true" data-show-export="true" data-page-size="100" data-height="500"
    data-pagination-loop="false" data-mobile-responsive="true" data-show-jump-to="true" data-buttons-class="amcr btn-xs"
    class="table table-hover table-borderless table-amcr">
    <!--Table head-->
    <thead scope="col" class="col-detectors-head">
        <tr>
            <th data-field="detail" data-width="50" data-halign="center" data-align="center">
                <i class="ti-new-window d-none d-sm-inline"></i>
                <span class="d-inline d-sm-none">{% trans "Detail nálezu" %}</span>
            </th>
            <th data-field="historie" data-width="50" data-halign="center" data-align="center">
                <i class="ti-timer d-none d-sm-inline"></i>
                <span class="d-inline d-sm-none">{% trans "Historie nálezu" %}</span>
            </th>
            <th data-field="ident_cely" data-sortable="true" data-align="left">{% trans "Nález" %}</th>
            <th data-field="stav" data-sortable="true" data-align="left">{% trans "Stav" %}</th>
            <th data-field="okres" class="table-short" data-sortable="true" data-align="left">{% trans "Okres" %}</th>
            <th data-field="katastr" class="table-short" data-sortable="true" data-align="left">{% trans "Katastr" %}</th>
            <th data-field="lokalizace" data-sortable="true" data-align="left">{% trans "Lokalizace" %}</th>
            <th data-field="obdobi" data-sortable="true" data-align="left">{% trans "Období" %}</th>
            <th data-field="druh_nalezu" data-sortable="true" data-align="left" class="table-short">{% trans "Nález" %}</th>
            <th data-field="specifikace" data-sortable="true" data-align="left">{% trans "Materiál" %}</th>
            <th data-field="nalezce" data-sortable="true" data-align="left">{% trans "Nálezce" %}</th>
            <th data-field="datum_nalezu" data-sortable="true" data-align="left" data-width="100">{% trans "Datum nálezu" %}</th>
            <th data-field="predano_organizace" data-sortable="true" data-align="left">{% trans "Uložení" %}</th>
            <th data-field="inv_cislo" data-sortable="true" data-align="left" data-width="140">{% trans "Evidenční číslo" %}</th>
            <th data-field="predano" data-sortable="true" data-align="left" data-width="90">{% trans "Předáno" %}</th>
            <th data-field="datum_vlozeni" data-sortable="true" data-align="left">{% trans "Datum zápisu" %}</th>
            <th data-field="datum_archivace" data-sortable="true" data-align="left">{% trans "Datum Archivace" %}</th>

        </tr>
    </thead>
    <!-- Table body -->
    <tbody>
        {% for row in table %}
        <tr>
            <td>
                <a class="icon-container" href="{% url 'pas:create' %}{{row.ident_cely}}" target="_blank" data-toggle="tooltip" data-placement="right" title="{% trans "Detail nálezu" %} {{row.ident_cely}}">
                    <i class="ti-new-window"></i>
                </a>
            </td>
            <td>
                <a class="icon-container" href="{% url 'pas:detectors_history' row.ident_cely %}" data-toggle="tooltip" data-placement="left" title="{% trans "Historie nálezu" %} {{row.ident_cely}}">
                    <i class="ti-timer"></i>
                </a>
            </td>
            <td>{{row.ident_cely}}</td>
            <td>{{row.stav}}</td>
            <td>{{row.okres}}</td>
            <td>{{row.katastr}}</td>
            <td>{{row.lokalizace}}</td>
            <td>{{row.obdobi}}</td>
            <td>{{row.druh_nalezu}}</td>
            <td>{{row.specifikace}}</td>
            <td>{{row.nalezce}}</td>
            <td>{{row.datum_nalezu}}</td>
            <td>{{row.predano_organizace}}</td>
            <td>{{row.inv_cislo}}</td>
            <td>{{row.predano}}</td>
            <td>{{row.datum_vlozeni}}</td>
            <td>{{row.datum_archivace}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- Table component END-->