webamcr/documents/urls.py
from django.urls import path

from . import views

app_name = 'documents'

urlpatterns = [
	path('', views.index, name="index"),
	path('create/', views.create, name="create"),
	path('create/<str:ident_cely>/', views.create, name="detail"),
	path('mymodels/', views.my_models, name='my_models'),
	path('manage/', views.manage_models, name='manage_models'),
	path('choose/', views.choose, name="choose"),
	path('upload/<int:pk>/', views.upload_file, name="upload_file"),
	path('name/create/', views.name_create, name="create_name"),
	path('finding/create/<str:ident_cely>/', views.finding_create, name="create_finding"),  # ident of the docuemnt component
	path('finding/update/<int:pk>/', views.finding_update, name="update_finding"),
	path('finding/delete/<int:pk>/', views.finding_delete, name='delete_finding'),
	path('author/edit/<str:ident_cely>/', views.author_edit, name="edit_author"),  # ident of the model
	path('return/<str:ident_cely>/', views.return_model, name="return_model"),
	path('history/<str:ident_cely>/', views.model_history, name="documents_history"),

	# API
	path('download_file/<int:pk>/', views.download_file, name='download_file'),  # id of the file
]

webamcr/webamcr/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from . import views
from documents.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('', views.home, name='home'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
	path('documents/', include('documents.urls')),
    path('pas/', include('detectors.urls')),
    path('django-rq/', include('django_rq.urls')),
    path('admin/', admin.site.urls),
    path('file/delete/<int:fileId>/', views.delete, name='delete_file'),
    path('user/', include('amcrusers.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

handler403 = 'webamcr.views.err_sid'

urlpatterns += staticfiles_urlpatterns()

webamcr/amcrusers/models.py
from django.db import models
from detectors.models import UserStorage
from detectors.constants import DetectorConstants as c


class HistorieUserStorage(models.Model):
    datum_zmeny = models.DateTimeField(auto_now_add=True, blank=False, null=False)
    typ_zmeny = models.IntegerField(default=0, choices=c.TYPY_ZMENY_USER_STORAGE, blank=False, null=False)
    ucet = models.ForeignKey(UserStorage, on_delete=models.CASCADE, related_name='historie_meho_uctu', blank=False, null=False)
    uzivatel = models.ForeignKey(UserStorage, on_delete=models.DO_NOTHING, related_name='zmeny_jinych_uctu', blank=False, null=False)
    komentar = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'historie_user_storage'

webamcr/documents/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.db.models import Q
from django.db import IntegrityError
from django.utils import translation

from . import xmlrpc
from . import helper
from .constants import AmcrConstants as c
from .decorators import login_required, min_user_group, permissions_required
from .forms import (FindingDocumentForm, AddNameForm, ChooseForm, CreateForm, LoginForm, EditAuthorForm)
from .models import (HeslarObjektDruh, HeslarPredmetDruh, HeslarTypNalezu, Dokument, HistorieDokumentu,
                     KomponentaDokument, HeslarObdobiDruha, HeslarArealDruha, NalezDokument, UserStorage,
                     ExtraData, JednotkaDokument, HeslarZeme, HeslarSpecifikaceObjektuDruha, HeslarSpecifikacePredmetu)
from detectors.models import HeslarJmena
from detectors.forms import ReturnFindingForm
from webamcr.views import heslar_organizace
from detectors.amcemails import email_send_3D1, email_send_3D2

import logging
import ftplib
import mimetypes
from datetime import datetime
from shapely import wkb


logger = logging.getLogger(__name__)

PREDMET_OPTION = 2
OBJEKT_OPTION = 1


@login_required
def upload_file(request, pk, **kwargs):

    context = {}
    sid = request.COOKIES.get('sessionId')
    dokument = Dokument.objects.get(pk=pk)
    context['ident_cely'] = dokument.ident_cely
    context['documentId'] = pk

    if request.method == 'POST' and request.FILES['myFile']:
        uploadedFile = request.FILES['myFile']

        try:
            xmlrpc.uploadDocumentFile(sid, dokument, uploadedFile)
            messages.add_message(request, messages.SUCCESS, c.FILE_UPLOADED_SUCCESSFULLY)
        except Exception as ex:
            logger.debug('Chyba pri uploadu souboru: ' + str(ex))
            messages.add_message(request, messages.WARNING, c.FILE_COULD_NOT_BE_UPLOADED)

        response = redirect('/documents/create/' + dokument.ident_cely)
    else:
        response = render(request, 'documents/uploadFile.html', {'context': context})

    return response


@login_required
def download_file(request, pk, **kwargs):

    sid = request.COOKIES.get('sessionId')
    try:
        name, f = xmlrpc.downloadFile(sid, pk)
        content_type = mimetypes.guess_type(name)[0]  # Use mimetypes to get file type
        f.seek(0)
        data = f.read()
        response = HttpResponse(data, content_type=content_type)
        response['Content-Length'] = str(len(data))
        response['Content-Disposition'] = "attachment; filename=%s" % name
        f.close()
    except (ftplib.all_errors, Exception):
        logger.debug('Chyba pri stahovani souboru')
        messages.add_message(request, messages.WARNING, c.FILE_COULD_NOT_BE_DOWNLOADED)
    else:
        return response


@login_required
def finding_update(request, pk, **kwargs):

    context = {}
    nalez = get_object_or_404(NalezDokument, pk=pk)
    ident_cely_dokument = nalez.komponenta_dokument.jednotka_dokument.dokument.ident_cely
    context['ident_cely'] = ident_cely_dokument
    context['detail'] = True

    if request.method == 'POST':
        form = FindingDocumentForm(request.POST)
        if form.is_valid():
            typ_nalezu_id = form.cleaned_data['typ_nalezu']
            druh_objektu_id = form.cleaned_data['druh_objektu']
            druh_predmetu_id = form.cleaned_data['druh_predmetu']
            specifikace_objektu_id = form.cleaned_data['specifikace_objektu']
            specifikace_predmetu_id = form.cleaned_data['specifikace_predmetu']
            poznamka = form.cleaned_data['poznamka']
            pocet = form.cleaned_data['pocet']

            if typ_nalezu_id:
                nalez.typ_nalezu = HeslarTypNalezu.objects.get(pk=typ_nalezu_id)
            if typ_nalezu_id == str(PREDMET_OPTION):
                nalez.druh_nalezu = druh_predmetu_id
                nalez.specifikace = specifikace_predmetu_id
            elif typ_nalezu_id == str(OBJEKT_OPTION):
                nalez.druh_nalezu = druh_objektu_id
                nalez.specifikace = specifikace_objektu_id
            else:
                logger.debug("Neznamy typ nelezu: " + str(typ_nalezu_id) + " <> " +
                             str(PREDMET_OPTION) + "/" + str(OBJEKT_OPTION))

            nalez.poznamka = poznamka
            nalez.pocet = pocet
            nalez.save()

            response = redirect('/documents/create/' + nalez.komponenta_dokument.jednotka_dokument.dokument.ident_cely)

        else:
            logger.debug("Form is not valid")
            logger.debug(form.errors)
            messages.add_message(request, messages.WARNING, c.FORM_IS_NOT_VALID)
    else:

        form_data = {
            'typ_nalezu': nalez.typ_nalezu.id,
            'poznamka': nalez.poznamka,
            'pocet': nalez.pocet,
        }
        if nalez.typ_nalezu.id == PREDMET_OPTION:
            form_data['druh_predmetu'] = nalez.druh_nalezu
            form_data['specifikace_predmetu'] = nalez.specifikace
        else:
            form_data['druh_objektu'] = nalez.druh_nalezu
            form_data['specifikace_objektu'] = nalez.specifikace

        form = FindingDocumentForm(initial=form_data)

        response = render(request, 'documents/finding.html', {
            'form': form,
            'context': context,
        })

    return response


@login_required
def finding_create(request, ident_cely, **kwargs):

    context = {}
    komponenta = get_object_or_404(KomponentaDokument, ident_cely=ident_cely)
    ident_cely_dokument = komponenta.jednotka_dokument.dokument.ident_cely
    context['ident_cely'] = ident_cely_dokument

    if request.method == 'POST':
        form = FindingDocumentForm(request.POST)
        if form.is_valid():
            typ_nalezu_id = form.cleaned_data['typ_nalezu']
            druh_objektu_id = form.cleaned_data['druh_objektu']
            druh_predmetu_id = form.cleaned_data['druh_predmetu']
            specifikace_objektu_id = form.cleaned_data['specifikace_objektu']
            specifikace_predmetu_id = form.cleaned_data['specifikace_predmetu']
            poznamka = form.cleaned_data['poznamka']
            pocet = form.cleaned_data['pocet']

            nalez = NalezDokument()

            if typ_nalezu_id:
                nalez.typ_nalezu = HeslarTypNalezu.objects.get(pk=typ_nalezu_id)
            if typ_nalezu_id == str(PREDMET_OPTION):
                nalez.druh_nalezu = druh_predmetu_id
                if specifikace_predmetu_id:
                    nalez.specifikace = specifikace_predmetu_id
            elif typ_nalezu_id == str(OBJEKT_OPTION):
                nalez.druh_nalezu = druh_objektu_id
                if specifikace_objektu_id:
                    nalez.specifikace = specifikace_objektu_id

            nalez.komponenta_dokument = komponenta
            nalez.poznamka = poznamka
            nalez.pocet = pocet
            nalez.save()
            logger.debug("Created finding: " + str(nalez.__dict__))
            messages.add_message(request, messages.SUCCESS, c.OBJECT_CREATED_SUCCESSFULLY)

            # redirect to create document
            response = redirect('/documents/create/' + ident_cely_dokument)

        else:
            logger.debug("Form is not valid")
            logger.debug(form.errors)
            messages.add_message(request, messages.WARNING, c.FORM_IS_NOT_VALID)
    else:

        form = FindingDocumentForm()
        response = render(request, 'documents/finding.html', {
            'form': form,
            'context': context,
        })

    return response

# user is admin


@login_required
def finding_delete(request, pk, **kwargs):

    nalez = NalezDokument.objects.get(pk=pk)
    ident_cely_dokument = nalez.komponenta_dokument.jednotka_dokument.dokument.ident_cely
    deleted = nalez.delete()

    if(deleted[0] > 0):
        logger.debug("Deleted finding object with id: " + str(pk) + ", " + str(deleted))
        messages.add_message(request, messages.SUCCESS, c.OBJECT_DELETED_SUCCESSFULLY)
    else:
        logger.debug("Could not find document finding object with id " + str(pk))
        messages.add_message(request, messages.WARNING, c.OBEJCT_COULD_NOT_BE_DELETED)

    return redirect('/documents/create/' + ident_cely_dokument)


@login_required
def name_create(request, **kwargs):

    if request.method == 'POST':
        form = AddNameForm(request.POST)
        if form.is_valid():

            jmena = form.cleaned_data['jmeno']
            prijmeni = form.cleaned_data['prijmeni']

            vypis = prijmeni + ','
            for j in jmena.split():
                vypis += ' ' + j.strip()[0].upper() + '.'

            try:
                jmeno = HeslarJmena(
                    jmeno=' '.join(jmena.split()),
                    prijmeni=prijmeni,
                    validated=True,
                    vypis=vypis,
                    vypis_cely=prijmeni + ', ' + jmena
                )
                jmeno.save()

                logger.debug("Nove jmeno pridano do heslare: " + jmeno.vypis)
                # Add message to the user
                messages.add_message(request, messages.SUCCESS, c.NAME_ADDED_TO_THE_LIST)
            except IntegrityError as ex:
                logger.debug(str(ex))
                messages.add_message(request, messages.WARNING, c.NAME_ALREADY_EXISTS)

            # redirect to the author edit form
            response = redirect(request.META['HTTP_REFERER'])
        else:
            logger.debug("Form is not valid.")
            logger.debug(form.errors)
            messages.add_message(request, messages.WARNING, c.FORM_IS_NOT_VALID)
    else:
        response = JsonResponse(-1, safe=False)

    return response


@login_required
def author_edit(request, ident_cely, **kwargs):

    MAX_AUTHOR_COUNT = 10
    sid = request.COOKIES.get('sessionId')
    addNameForm = AddNameForm()

webamcr/documents/templates/components/button-group.html
{% load i18n %}
<div class="button-group mb-md-3 mr-1 ml-1">
    <div class="row mt-2 pr-0 pr-md-2">
        {% if not context.showDetails %}
        <div class="col col-md-2">
            <button name="button_return" type="button" class="btn btn-amcr-3d btn-block checkchanges" onclick="goBack()">{% trans "Zpět" %}</button>
        </div>
        {% else %}
        <div class="col col-md-2">
            <button name="button_close" type="button" class="btn btn-amcr-3d btn-block closeTab">{% trans "Zavřít" %}</button>
        </div>
        {% endif %}
        {% if context.canEdit and context.showDetails %}
        <div class="col-6 col-md-2">
            <a class="btn btn-amcr-3d btn-block" data-toggle="modal"
                data-target="#deleteDocument3d">{% trans "Smazat" %}</a>
        </div>
        {% endif %}
        {% if context.canReturn %}
        <div class="col-6 col-md-2 mt-2 mt-md-0">
            <a class="btn btn-amcr-3d btn-block checkchanges" href="{% url 'documents:return_model' ident_cely %}">{% trans "Vrátit" %}</a>
        </div>
        {% elif context.showDetails %}
        <div class="col-6 col-md-2 mt-2 mt-md-0">
            <button type="button" class="btn btn-amcr-3d btn-block disabled" disabled="true">{% trans "Vrátit" %}</button>
        </div>
        {% endif %}

    </div>
    <div class="row mt-2 pr-0 pr-md-2">
        {% if context.canArchive %}
        <div class="col-6 col-md-2">
            <button type="button" class="btn btn-amcr-3d btn-block checkchanges" data-toggle="modal"
                data-target="#send_to_archive" name="button_archive">{% trans "Archivovat" %}</button>
        </div>
        {% elif context.showDetails %}
        <div class="col-6 col-md-2">
            <button type="button" class="btn btn-amcr-3d btn-block disabled" disabled="true">{% trans "Archivovat" %}</button>
        </div>
        {% endif %}


        {% if context.showDetails %}
        <div class="col-6 col-md-2">
            <a class="btn btn-amcr-3d btn-block checkchanges"
                href="{% url 'documents:documents_history' ident_cely %}">{% trans "Historie" %}</a>
        </div>
        {% endif %}
    </div>
</div>

webamcr/documents/templates/components/changed-form-modal.html
{% load i18n %}

<!-- Changes modal -->
<div class="modal fade" id="formChangeModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans "Formulář byl editován" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>{% trans "Ve formuláři jsou neuložené změny." %}</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-amcr-3d btn-block" href="{% url 'documents:detail' ident_cely %}">{% trans "Zahodit změny" %}</a>
        <button class="btn btn-amcr-3d btn-block" name="button_save">{% trans "Uložit změny" %}</button>
      </div>
    </div>
  </div>
</div>

webamcr/documents/templates/components/changed-from-modal.html
{% load i18n %}

<!-- Changes modal -->
<div class="modal fade" id="formChangeModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans "Formulář byl editován" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>{% trans "Ve formuláři jsou neuložené změny." %}</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-amcr-3d btn-block" href="{% url 'documents:detail' ident_cely %}">{% trans "Zahodit změny" %}</a>
        <button class="btn btn-amcr-3d btn-block" name="button_save">{% trans "Uložit změny" %}</button>
      </div>
    </div>
  </div>
</div>

webamcr/documents/templates/components/doc-table.html
{% load i18n %}
{% load amcr_tags %}
{% get_current_language as LANGUAGE_CODE %}
<table id="documents_table" data-locale="{{ LANGUAGE_CODE }}" data-min-width="560" data-toggle="table" data-toolbar="#toolbar"
    data-pagination="true" data-show-pagination-switch="true" data-pagination-pre-text="{% trans "Předchozí" %}" data-pagination-next-text="{% trans "Další" %}"
    data-show-columns="true" data-show-toggle="true" data-show-export="true" data-page-size="100" data-pagination-loop="false"
    data-mobile-responsive="true" data-show-jump-to="true" data-search="true" data-buttons-class="amcr-3d btn-xs"
    class="table table-hover table-borderless table-amcr">
    <!--Table head-->
    <!--Table head-->
    <thead scope="col" class="col-documents col-documents-head">
        <tr>
            <th data-field="detail" data-width="50" data-halign="center" data-align="center">
                <i class="ti-new-window d-none d-sm-inline"></i>
                <span class="d-inline d-sm-none">{% trans "Detail modelu" %}</span>
            </th>
            <th data-field="historie" data-width="50" data-halign="center" data-align="center">
                <i class="ti-timer d-none d-sm-inline"></i>
                <span class="d-inline d-sm-none">{% trans "Historie modelu" %}</span>
            </th>
            <th data-field="ident_cely" data-sortable="true">{% trans "ID" %}</th>
            <th data-field="stav" data-sortable="true">{% trans "Stav" %}</th>
            <th data-field="typ_dokumentu" data-sortable="true">{% trans "Typ dokumentu" %}</th>
            <th data-field="organizace_autora" data-sortable="true">{% trans "Organizace autora" %}</th>
            <th data-field="autor" data-sortable="true">{% trans "Autor" %}</th>
            <th data-field="rok_vzniku" data-sortable="true">{% trans "Rok vzniku" %}</th>
            <th data-field="zeme" data-sortable="true">{% trans "Zeme" %}</th>
            <th data-field="region" data-sortable="true">{% trans "Region" %}</th>
            <th data-field="odkaz" data-sortable="true">{% trans "Odkaz" %}</th>
            <th data-field="duveryhodnost" data-sortable="true">{% trans "Důvěryhodnost" %}</th>
            <th data-field="datum_vlozeni" data-sortable="true">{% trans "Datum vložení" %}</th>
            <th data-field="datum_archivace" data-sortable="true">{% trans "Datum Archivace" %}</th>

        </tr>
    </thead>
    <tbody>
        {% for row in context.table %}
        <tr>
            <td>
                <a class="icon-container" href="{% url 'documents:create' %}{{row.ident_cely}}" target="_blank" data-toggle="tooltip"
                    data-placement="right" title="{% trans "Detail modelu" %} {{row.ident_cely}}">
                    <i class="ti-new-window"></i>
                </a>
            </td>
            <td>
                <a class="icon-container" href="{% url 'documents:documents_history' row.ident_cely %}" data-toggle="tooltip" data-placement="left" title="{% trans "Historie modelu" %} {{row.ident_cely}}">
                    <i class="ti-timer"></i>
                </a>
            </td>
            <td scope="row">{{row.ident_cely}}</td>
            <td>{{context.doc_states|get_item:row.stav}}</td>
            {% if LANGUAGE_CODE == 'en' %}
                <td>{{row.typ_dokumentu.en}}</td>
            {% else %}
                <td>{{row.typ_dokumentu.nazev}}</td>
            {% endif %}
            <td>{{context.org_dict|get_item:row.organizace}}</td>
            <td>{{row.autor}}</td>
            <td>{{row.rok_vzniku}}</td>
            {% if LANGUAGE_CODE == 'en' %}
                <td>{{row.extradata.zeme.nazev_en}}</td>
            {% else %}
                <td>{{row.extradata.zeme.nazev}}</td>
            {% endif %}
            <td>{{row.extradata.region|default_if_none:"" }}</td>
            <td>{{row.extradata.odkaz|default_if_none:""}}</td>
            <td>{{row.extradata.duveryhodnost}} %</td>
            <td>{{row.datum_vlozeni|epoch_timestamp_to_datetime}}</td>
            <td>{{row.datum_archivace|epoch_timestamp_to_datetime}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

webamcr/documents/templates/components/file-unit-buttons.html
{% load i18n %}
<button class="btn btn-secondary btn-block" href="javascript:void(0)">{% trans "Uložit změny" %}</button>
<hr class="separator">
<div class="pt-2">
    <button class="btn btn-secondary btn-block" href="javascript:void(0)">{% trans "Přidat komponentu" %}</button>
</div>

webamcr/documents/templates/components/files-buttons.html
{% load i18n %}
<div>
    <button class="btn btn-secondary btn-block" href="javascript:void(0)" id="addScnt">{% trans "Stáhnout" %}</button>
</div>
<div class="pt-2">
    <button class="btn btn-secondary btn-block" href="javascript:void(0)">{% trans "Odstranit" %}</button>
</div>

webamcr/documents/templates/components/finding-table.html
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
{% block head %}
<script src="{% static "/js/bootstrap-table-mobile.min.js" %}"></script>
{% endblock %}
<table id="finding_table" data-locale="{{LANGUAGE_CODE}}" data-toggle="table" data-mobile-responsive="true"
    class="table table-hover table-borderless table-amcr file-table">
    <!--Table head-->
    <thead scope="col" id="finding_table_header" class="col-documents-head">
        <tr>
            <th data-field="detail" data-halign="center" data-align="center">{% trans "Detail" %}</th>
            <th data-field="typ" class="table-short" data-sortable="true">{% trans "Typ nálezu" %}</th>
            <th data-field="druh" class="table-short" data-sortable="true">{% trans "Druh nálezu" %}</th>
            <th data-field="specifikace" class="table-short" data-sortable="true">{% trans "Specifikace" %}</th>
            <th data-field="pocet" class="table-short" data-sortable="true">{% trans "Počet" %}</th>
            <th data-field="poznamka" class="table-long" data-sortable="true">{% trans "Poznámka" %}</th>
            <th data-field="smazat" data-halign="left" data-align="center">{% trans "Smazat" %}</th>
        </tr>
    </thead>
    <!--Table head-->
    <!--Table body-->
    <tbody>
        {% for row in context.nalezy %}
        <tr>
            <td>
                {% if context.canEdit %}
                <a class="icon-container checkchanges" href="{% url 'documents:update_finding' row.id %}"
                    data-toggle="tooltip" data-placement="right" title="{% trans "Detail nálezu" %}">
                    <i class="ti-new-window"></i>
                </a>
                {% else %}
                <i class="ti-new-window icon-disabled"></i>
                {% endif %}
                </a>
            </td>
            <td>{{row.typ_nalezu}}</td>
            <td>{{row.druh_nalezu}}</td>
            <td>{{row.specifikace|default_if_none:""}}</td>
            <td>{{row.pocet}}</td>
            <td>{{row.poznamka}}</td>
            <td>
                {% if context.canEdit %}
                <a class="icon-container checkchanges" data-toggle="modal" data-target="#delete_finding-{{row.id}}"><i
                        class="ti-close" data-toggle="tooltip" data-placement="left"
                        title="{% trans "Smazat nález" %}"></i></a>
                {% else %}
                <i class="ti-close icon-disabled"></i>
                {% endif %}
            </td>
            <!-- MODAL DELETE PHOTO -->
            <div class="modal fade" id="delete_finding-{{row.id}}" tabindex="-1" role="dialog"
                aria-labelledby="deleteFindingTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteFindingTitle">{% trans "Smazat nález" %}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                        </div>
                        <div class="modal-body">
                            <p>{% trans "Opravdu chcete tento nález smazat?" %}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-amcr-3d btn-block"
                                data-dismiss="modal">{% trans "Ne" %}</button>
                            <a class="btn btn-amcr-3d btn-block"
                                href="{% url 'documents:delete_finding' row.id %}">{% trans "Ano" %}</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END OF MODAL DELETE PHOTO-->
        </tr>
        <!-- End of modal - delete photo -->
        {% endfor %}
    </tbody>
    <!--Table body-->
</table>

webamcr/documents/templates/components/history_table_doc.html
{% load i18n %}
{% load tz %}
{% get_current_language as LANGUAGE_CODE %}
<!--Table-->
<table id="history_table_doc" data-locale="{{ LANGUAGE_CODE }}" data-toggle="table" data-toolbar="#toolbar" data-pagination="true" data-pagination-pre-text="{% trans "Předchozí" %}" data-show-pagination-switch="true" data-pagination-loop="false"
    data-pagination-next-text="{% trans "Další" %}" data-show-columns="true" data-show-toggle="true" data-show-export="true" data-mobile-responsive="true" data-search="true" data-buttons-class="amcr-3d btn-xs"
    class="table table-hover table-borderless">
    <!--Table head-->
    <thead scope="col" class="col-documents col-documents-head">
        <tr>
            <th data-field="datum_zmeny" data-sortable="true">{% trans "Datum změny" %}</th>
            <th data-field="typ_zmeny" data-sortable="true">{% trans "Typ změny" %}</th>
            <th data-field="uzivatel" data-sortable="true">{% trans "Uživatel" %}</th>
            <th data-field="ident" data-sortable="true">{% trans "Identifikátor" %}</th>
            <th data-field="organizace" data-sortable="true">{% trans "Organizace" %}</th>
            <th data-field="duvod" data-sortable="true">{% trans "Komentář" %}</th>
        </tr>
    </thead>
    <!--Table head-->
    <!--Table body-->
    <tbody class="table-md">
        {% for s in historie %}
        <tr>
            <td>{{s.datum_zmeny|timezone:"Europe/Prague"|date:'Y-m-d H:i' }}</td>
            <td>{{s.get_typ_zmeny_display}}</td>
            <td>{{ s.uzivatel.prijmeni }}, {{s.uzivatel.jmeno}}</td>
            <td>{{ s.uzivatel.ident_cely }}</td>
            <td>{{ s.uzivatel.organizace.nazev_zkraceny }}</td>
            <td>{{s.duvod}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <!--Table body-->
</table>

webamcr/documents/templates/components/table-script-doc-history.html
<script>
    $(document).ready(function () {
        //History Table
        var $table_history = $('#history_table_doc')
        $table_history.bootstrapTable('refreshOptions',{
            exportTypes: ['csv', 'xml', 'json'],
            exportOptions: {
                fileName: function () {
                    return getExportDate()
                }
            }
        })
    })
</script>