webamcr/detectors/urls.py
from django.urls import path

from . import views

app_name = 'pas'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('create/<str:ident_cely>/', views.create, name="detail"),
    path('history/<str:ident_cely>/', views.historyDetectorsList, name="detectors_history"),
    path('choose/', views.choose, name="choose"),
    path('myfinds/', views.my_detectors, name='moje_list'),
    path('cooperate/', views.cooperate, name="cooperate"),
    path('cooperate/update/<int:pk>/', views.updateCooperation, name="cooparate_update"),
    path('cooperate/create/', views.createCooperation, name="cooparate_create"),
    path('cooperate/delete/<int:pk>/', views.deleteCooperation, name="cooparate_delete"),
    path('cooperate/history/<int:pk>/', views.historyCooperationList, name='cooperate_history'),
    path('confirm/', views.confirm, name="confirm"),  # list findings to be confirmed
    path('archive/', views.archive, name="archive"),  # list findings to be archived
    path('return/<str:ident_cely>/', views.return_finding, name="return_finding"),

    path('file/upload/<int:projectId>/<str:findingIdentCely>/', views.upload, name="upload"),
]

webamcr/webamcr/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from . import views
from documents.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('', views.home, name='home'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
	path('documents/', include('documents.urls')),
    path('pas/', include('detectors.urls')),
    path('django-rq/', include('django_rq.urls')),
    path('admin/', admin.site.urls),
    path('file/delete/<int:fileId>/', views.delete, name='delete_file'),
    path('user/', include('amcrusers.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

handler403 = 'webamcr.views.err_sid'

urlpatterns += staticfiles_urlpatterns()

webamcr/detectors/views.py
import logging
import subprocess

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.utils import translation

from detectors import helper as helper_det
from documents.constants import AmcrConstants as c
from documents import helper as helper_doc
from documents import xmlrpc
from documents.forms import AddNameForm
from documents.decorators import login_required, min_user_group
from documents.models import (HeslarPredmetDruh, HeslarObdobiDruha,
    HeslarSpecifikacePredmetu)
from webamcr import helper_general
from webamcr.views import heslar_organizace

from . import connector
from . import amcemails
from django.core.files import File
from .constants import DetectorConstants as det_const
from . import models
from .forms import (CreateCooperateForm, UpdateCooperateForm,
                    make_ChooseDetectorForm, make_CreateDetectorForm, ReturnFindingForm)
from io import BytesIO


logger = logging.getLogger(__name__)


@login_required
def upload(request, projectId, findingIdentCely, **kwargs):

    sid = request.COOKIES.get('sessionId')
    nalez = models.SamostatnyNalez.objects.get(ident_cely=findingIdentCely)

    if request.method == 'POST' and request.FILES['myFile']:
        uploadedFile = request.FILES['myFile']
        originalName = uploadedFile.name

        # Check if the file type is allowed
        logger.debug("File name: " + str(originalName))
        allowed_types = ['.jpg', '.jpeg', '.tiff', '.tif', '.png']
        allowed_type = False
        for i in allowed_types:
            if uploadedFile.name.lower().endswith(i):
                allowed_type = True
                break
        if not allowed_type:
            messages.add_message(request, messages.WARNING, _("Pouze soubory typu jpg, tiff a png je možné nahrávat."))
            return render(request, 'detectors/uploadFile.html', {'findingIdentCely': findingIdentCely})
        # Remove EXIF data using exiftools
        args = ['exiftool', '-All=', '-']
        p = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        out, err = p.communicate(input=uploadedFile.read())
        sanitized_image = BytesIO(out)
        f_new = File(sanitized_image)
        f_new.name = originalName

        resp = xmlrpc.uploadProjectFile(sid, projectId, f_new, nalez)
        if resp:
            soubor = models.Soubor.objects.get(pk=resp[0])
            soubor.samostatny_nalez = nalez
            soubor.uzivatelske_oznaceni = originalName
            soubor.projekt = None
            soubor.save()
        else:
            logger.warning('Chyba pri uploadu souboru')

        return redirect('/pas/create/' + findingIdentCely)
    return render(request, 'detectors/uploadFile.html', {'findingIdentCely': findingIdentCely})


@login_required
@csrf_protect
def index(request, **kwargs):
    response = render(request, 'detectors/index.html')
    return response


def logout(request):
    response = redirect('login')
    response.delete_cookie('sessionId')
    response.delete_cookie('lstamp')
    return response


@login_required
def create(request, ident_cely='0', **kwargs):
    projekt_id = []
    user_sid = request.COOKIES.get('sessionId')
    current_user = kwargs['user']
    user_id = str(current_user['id'])
    user = get_object_or_404(models.UserStorage, pk=user_id)
    if request.method == 'POST':
        # create FORM
        form = make_CreateDetectorForm(user_id, user_sid, request.POST)

        if form.is_valid():
            detector_project = form.data.get('detector_project')
            detector_localization = form.data.get('detector_localization')
            detector_coordinates_x = form.data.get('detector_coordinates_x')
            detector_coordinates_y = form.data.get('detector_coordinates_y')
            detector_finder = form.data.get('detector_finder')
            detector_find_date = form.data.get('detector_find_date')
            detector_circumstances = form.data.get('detector_circumstances')
            detector_depth = form.data.get('detector_depth')
            detector_dating = form.data.get('detector_dating')
            detector_exact_dating = form.data.get('detector_exact_dating')
            detector_kind = form.data.get('detector_kind')
            detector_material = form.data.get('detector_material')
            detector_quantity = form.data.get('detector_quantity')
            detector_note = form.data.get('detector_note')
            detector_organisation_passed = form.data.get('detector_organisation_passed')
            detector_evidence_number = form.data.get('detector_evidence_number')
            detector_find_passed = form.data.get('detector_find_passed')
            detector_accessibility = form.data.get('detector_accessibility')

            params = {}
            if (detector_project):
                params['projekt'] = str(detector_project)
            if (detector_localization):
                params['lokalizace'] = str(detector_localization)
            params['katastr'] = '-1'
            if (detector_coordinates_x and detector_coordinates_y):
                params['zswgs'] = str(detector_coordinates_x)
                params['zdwgs'] = str(detector_coordinates_y)
            if (detector_finder):
                params['nalezce'] = str(detector_finder)
            if (detector_find_date):
                params['datum_nalezu'] = helper_doc.date_to_psql_date(str(detector_find_date))
            else:
                params['datum_nalezu'] = '__NULL__'
            if (detector_circumstances):
                params['okolnosti'] = str(detector_circumstances)
            else:
                params['okolnosti'] = '__NULL__'
            if (detector_depth):
                params['hloubka'] = str(detector_depth)
            if (detector_dating):
                params['obdobi'] = str(detector_dating)
            else:
                params['obdobi'] = '__NULL__'
            if (detector_exact_dating):
                params['presna_datace'] = str(detector_exact_dating)
            if (detector_kind):
                params['druh_nalezu'] = str(detector_kind)
            else:
                params['druh_nalezu'] = '__NULL__'
            if (detector_material):
                params['specifikace'] = str(detector_material)
            else:
                params['specifikace'] = '__NULL__'
            if (detector_quantity):
                params['pocet'] = str(detector_quantity)
            if (detector_note):
                params['poznamka'] = str(detector_note)
            if (detector_organisation_passed):
                params['predano_organizace'] = str(detector_organisation_passed)
            if (detector_evidence_number):
                params['inv_cislo'] = str(detector_evidence_number)
            if (detector_find_passed):
                if str(detector_find_passed) == 'True':
                    params['predano'] = 'true'
                else:
                    params['predano'] = 'false'
            if (detector_accessibility):
                params['pristupnost'] = str(detector_accessibility)

            if(ident_cely == '0'):
                # I am creating the object
                ret = helper_det.zapsani(params, user, user_sid)

                if ret:
                    ident_cely = ret.ident_cely
                    messages.add_message(request, messages.SUCCESS, c.OBJECT_CREATED_SUCCESSFULLY)
                else:
                    ident_cely = ''
                    logger.error("Nepovedlo se vytvorit samostatny nalez")
                    messages.add_message(request, messages.WARNING, c.OBEJCT_COULD_NOT_BE_CREATED)
            else:
                params['ident_cely'] = ident_cely
                nalez = models.SamostatnyNalez.objects.get(ident_cely=ident_cely)
                params['id'] = nalez.id
                params['stav'] = nalez.stav

                if 'button_save' in request.POST:
                    ret = helper_det.update(params, nalez, user, user_sid)
                elif 'button_send_to_confirm' in request.POST:
                    ret = helper_det.odeslani(params, nalez, user, user_sid)
                elif 'button_confirm' in request.POST:
                    ret = helper_det.potvrzeni(params, nalez, user, user_sid)
                elif 'button_archive' in request.POST:
                    ret = helper_det.archivace(params, nalez, user, user_sid)
                else:
                    logger.debug("Unknown post request button type")

                if 'button_delete' in request.POST:
                    resp = nalez.delete()
                    if resp[0] > 0:
                        logger.debug("Objekt " + str(resp) + ' smazán')
                        messages.add_message(request, messages.SUCCESS, c.OBJECT_DELETED_SUCCESSFULLY)
                        return redirect('/pas/create/')
                    else:
                        messages.add_message(request, messages.WARNING, c.OBEJCT_COULD_NOT_BE_DELETED)

            return redirect('/pas/create/' + ident_cely)

        logger.warning('Form create is not valid')
        logger.warning(form.errors)
        logger.warning(form.non_field_errors)
        return render(request, 'detectors/create.html', {'formDetCreate': form})

    elif request.method == 'GET':
        addNameForm = AddNameForm()
        context = {}
        if(ident_cely == '0'):
            formDetCreate = make_CreateDetectorForm(user_id, user_sid, initial={
                'detector_find_passed': False,

webamcr/detectors/templates/detectors/cooperate.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block head %}
<script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.15.5/dist/extensions/export/bootstrap-table-export.min.js"></script>
<script src="{% static "/js/bootstrap-table-mobile.min.js" %}"></script>
{% endblock %}
{% block content %}
<script>
    $('.menu_detectors').addClass('active')
    $('.menu_cooperate_det').addClass('active')
</script>
<!-- page title area start -->
<div class="page-title-area title-det mb-4">
    <div class="row align-items-center">
        <div class="col-sm-12">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title d-block d-sm-block d-md-block d-lg-none">{{MODUL_DETECTOR}}</h4>
                <h4 class="page-title pull-left d-none d-lg-block">{{MODUL_DETECTOR}}</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/" class="main-modul-det">{{MAIN_MENU}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
                    <li><a href="/pas/" class="main-modul-det">{{MODUL_DETECTOR}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
                    <li><a href="/pas/cooperate/" class="main-modul-det">{{COOP_DETECTOR}}</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content-inner mr-2 ml-2 mb-2">
    <div class="card">
        <div class="card-body">
            <div class="coop-table table-det">
                <div id="toolbar" class="pagewrap">
                    <!-- Top pagination detail -->
                    <a href="{% url 'pas:cooparate_create' %}" class="btn btn-amcr btn-xs"><i class="pr-2 ti-user"></i>{% trans "Nová žádost o spolupráci" %}</a>
                </div>
                {% include "components/spoluprace_table.html" %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
    $(document).ready(function () {
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })

        var $table = $('#coop_table')
        //Export data types
        $table.bootstrapTable('refreshOptions',{
            exportTypes: ['csv', 'xml', 'json'],
            exportOptions: {
                fileName: function () {
                    return getExportDate()
                },
                ignoreColumn: ['detail', 'historie']
            }
        })
    })
</script>
{% endblock %}

webamcr/detectors/templates/detectors/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<script>
    $('.menu_detectors').addClass('active')
    $('.menu_home_det').addClass('active')
</script>
<!-- page title area start -->
<div class="page-title-area title-det mb-3">
    <div class="row align-items-center">
        <div class="col-sm-12">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title d-block d-sm-block d-md-block d-lg-none">{{MODUL_DETECTOR}}</h4>
                <h4 class="page-title pull-left d-none d-lg-block">{{MODUL_DETECTOR}}</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/" class="main-modul-det">{{MAIN_MENU}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
                    <li><a href="" class="main-modul-det">{{MODUL_DETECTOR}}</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content-inner mr-2 ml-2">
    <!-- Main menu CARD area start -->
    <div class="row mt-4 mb-5">
        <div class="owl-carousel owl-theme">
            <!-- Detector - Create -->
            <div class="amcr-card cardhover create-det">
                <a href="{% url 'pas:create' %}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-detektor.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{CREATE_ENTRY}}</h2>
                        </div>
                    </div>
                </a>
            </div>
            <!-- Detector - My detectors -->
            {% with 'Badatel Archeolog Archivář Admin' as list_badatel %}
            {% if userDetail.role_opravneni.role in list_badatel %}
            <div class="amcr-card cardhover my-det">
                <a href="{% url 'pas:moje_list' %}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-detektor.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{MY_FINDS}}</h2>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endwith %}
            <!-- Detector - Choose -->
            <div class="amcr-card cardhover choose-det">
                <a href="{% url 'pas:choose' %}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-detektor.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{CHOOSE_ENTRY}}</h2>
                        </div>
                    </div>
                </a>
            </div>
            <!-- Detector - Cooperation -->
            <div class="amcr-card cardhover coop-det">
                <a href="{% url 'pas:cooperate' %}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-detektor.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{COOP_DETECTOR}}</h2>
                        </div>
                    </div>
                </a>
            </div>
            <!-- Detector - Confirm -->
            {% with 'Archeolog Archivář Admin' as list_archeolog %}
            {% if userDetail.role_opravneni.role in list_archeolog %}
            <div class="amcr-card cardhover confirm-det">
                <a href="{% url 'pas:confirm' %}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-detektor.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{CONFIRM_DETECTOR}}
                            </h2>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endwith %}
            <!-- Detector - Archive -->
            {% with 'Archivář Admin' as list_archivar %}
            {% if userDetail.role_opravneni.role in list_archivar %}
            <div class="amcr-card cardhover archive-det">
                <a href="{% url 'pas:archive' %}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-detektor.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{ARCHIVE_DETECTOR}}
                            </h2>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <!-- Texts related to cards -->
    <div class="card-text-wrapper text-justify col-12 col-md-11">
        <!-- Create detector text -->
        <div class="create-det d-none">
            <p><strong>{% trans "AMČR PAS - Zapsat" %}</strong></p>
            <hr>
            <p>{% trans "Slouží k zápisu nového nálezu. Pro zápis nálezu je třeba mít navázanou spolupráci s konkrétním archeologem oprávněným provádět archeologické výzkumy a znát číslo odpovídajícího terénního projektu. K nálezu je třeba dále vložit jeho fotografii, lokalizaci a základní popisné údaje." %}
                <strong>{% trans "Každý takto evidovaný nález musí být v souladu s památkovým zákonem získán ve spolupráci s oprávněnou organizací a následně předán do její správy." %}</strong></p>
        </div>
        <!-- My detector text -->
        <div class="my-det d-none">
            <p><strong>{% trans "AMČR PAS - Moje" %}</strong></p>
            <hr>
            <p>{% trans "Nabídka badateli zobrazí výčet jeho evidovaných nálezů, archeologovi nabízí seznam samostatných nálezů od spolupracovníků jeho oprávněné organizace." %}</p>
        </div>
        <!-- Choose detector text -->
        <div class="choose-det d-none">
            <p><strong>{% trans "AMČR PAS - Vybrat" %}</strong></p>
            <hr>
            <p>{% trans "Slouží k výběru vašich nálezů podle zadaných kritérií (pro badatele), k výběru nálezů vaší oprávněné organizace (pro archeologa), případně k procházení všech evidovaných nálezů (pro archiváře). K celkovému procházení a prohledávání všech evidovaných nálezů slouží aplikace Digitální archiv AMČR (https://digiarchiv.aiscr.cz/)." %}</p>
        </div>
        <!-- Coop detector text -->
        <div class="coop-det d-none">
            <p><strong>{% trans "AMČR PAS - Spolupráce" %}</strong></p>
            <hr>
            <p>{% trans "Zde může badatel zřizovat nové vazby na archeology a archeolog potvrzovat žádosti o spolupráci. Jeden badatel může mít vazbu na neomezené množství archeologů/institucí, archeolog může mít neomezené množství spolupracovníků. Vazby lze zpětně deaktivovat." %}</p>
        </div>
        <!-- Confirm detector text -->
        <div class="confirm-det d-none">
            <p><strong>{% trans "AMČR PAS - Potvrdit" %}</strong></p>
            <hr>
            <p>{% trans "Výčet samostatných nálezů od spolupracovníků vaší organizace čekajících na potvrzení. "%}</p>
        </div>
        <!-- Archive detector text -->
        <div class="archive-det d-none">
            <p><strong>{% trans "AMČR PAS - Archivovat" %}</strong></p>
            <hr>
            <p>{% trans "Výčet všech nálezů potvrzených archeologem čekajících na archivaci a zveřejnění." %}</p>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            //cards- text on hover
            card_text();
            //slider init
            create_slider();
        })
    </script>
{% endblock %}

webamcr/detectors/templates/detectors/uploadFile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
<script>
  $('.menu_detectors').addClass('active')
  $('.menu_create_det').addClass('active')
</script>
<!-- page title area start -->
<div class="page-title-area title-det mb-4">
  <div class="row align-items-center">
    <div class="col-sm-12">
      <div class="breadcrumbs-area clearfix">
        <h4 class="page-title d-block d-sm-block d-md-block d-lg-none">{{MODUL_DETECTOR}}</h4>
        <h4 class="page-title pull-left d-none d-lg-block">{{MODUL_DETECTOR}}</h4>
        <ul class="breadcrumbs pull-left">
          <li><a href="/" class="main-modul-det">{{MAIN_MENU}}</a></li>
        </ul>
        <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
          <li><a href="/pas/" class="main-modul-det">{{MODUL_DETECTOR}}</a></li>
        </ul>
        <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
          <li><a href="/pas/create/" class="main-modul-det">{{CREATE_ENTRY}}</a></li>
        </ul>
        <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
          <li><p class="main-modul-det">{{UPLOAD}}</p></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="main-content-inner mb-5">
  <div class="form-row">
    <div class="col-12 col-md-11 col-lg-10 col-xl-6">
      <p class="h2 font-weight-light card-heading ml-0">{% trans "Nahrání fotografie" %}</p>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card create-card m-0">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <button type="submit" class="btn btn-amcr" id="fileUpload"
                      onclick="return Uploadcheck()">{% trans "Nahrát" %}</button>
                  </div>
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" lang="{{LANGUAGE_CODE}}" name="myFile" accept="image/*" id="detector_upload">
                    <label class="custom-file-label" for="detector_upload">{% trans "Vyberte soubor" %}</label>
                  </div>
                  <p class="mt-3 text-secondary">{% trans "Nahráním souboru udělujete souhlas s jeho trvalým využitím a šířením pod licencí" %} <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">{% trans "Creative Commons Uveďte původ-Neužívejte komerčně 4.0 Mezinárodní (CC BY-NC 4.0)" %}</a>.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
      <img id="detector_upload_preview" class="mt-2">
      <div class="col-12 pl-0">
        <a class="btn btn-amcr mt-2" href="{% url 'pas:detail' findingIdentCely %}">{% trans "Zpět" %}</a>
      </div>
    </div>
  </div>

  <!-- Modals -->
  <!-- Wrong File modal -->
  <div class="modal fade" id="wrongFile" tabindex="-1" role="dialog" aria-labelledby="wrongFileLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="wrongFileLabel">{% trans "Špatný typ souboru" %}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="text-center">{% trans "Pro samostatný nález můžete nahrát pouze obrázky." %}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-amcr btn-block" data-dismiss="modal">{% trans "OK" %}</button>
        </div>
      </div>
    </div>
  </div>
  <!-- Empty File modal -->
  <div class="modal fade" id="emptyUpload" tabindex="-1" role="dialog" aria-labelledby="emptyUploadLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="emptyUploadLabel">{% trans "Nevybrán žádný soubor" %}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>{% trans "Vyberte soubor, který chcete k nálezu nahrát" %}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-amcr btn-block" data-dismiss="modal">{% trans "OK" %}</button>
        </div>
      </div>
    </div>
  </div>
  <!-- Modals end -->
  {% endblock %}

  {% block script %}
  <script>
    //Upload empty field validation check
    function Uploadcheck() {
      var uploadFile = document.getElementById('detector_upload');
      if (uploadFile.value === null || uploadFile.value === "") {
        $('#emptyUpload').modal('show')
        return false;
      }
      else {
        return true
      }
    }

    //Image type validation and preview
    document.getElementById("detector_upload").onchange = function () {
      var reader = new FileReader();
      if (this.files[0].type.indexOf("image") == -1) {
        $('#wrongFile').modal('show');
        $("#detector_upload_preview").attr("src", "blank");
        $("#detector_upload_preview").hide();
        $('#detector_upload').wrap('<form>').closest('form').get(0).reset();
        $('#detector_upload').unwrap();
        return false;
      }
      reader.onload = function (e) {
        document.getElementById("detector_upload_preview").src = e.target.result;
      };
      reader.readAsDataURL(this.files[0]);
    };

    // Name of file appear in selection
    $(".custom-file-input").on("change", function () {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
  </script>
  {% endblock %}