webamcr/documents/urls.py
from django.urls import path

from . import views

app_name = 'documents'

urlpatterns = [
	path('', views.index, name="index"),
	path('create/', views.create, name="create"),
	path('create/<str:ident_cely>/', views.create, name="detail"),
	path('mymodels/', views.my_models, name='my_models'),
	path('manage/', views.manage_models, name='manage_models'),
	path('choose/', views.choose, name="choose"),
	path('upload/<int:pk>/', views.upload_file, name="upload_file"),
	path('name/create/', views.name_create, name="create_name"),
	path('finding/create/<str:ident_cely>/', views.finding_create, name="create_finding"),  # ident of the docuemnt component
	path('finding/update/<int:pk>/', views.finding_update, name="update_finding"),
	path('finding/delete/<int:pk>/', views.finding_delete, name='delete_finding'),
	path('author/edit/<str:ident_cely>/', views.author_edit, name="edit_author"),  # ident of the model
	path('return/<str:ident_cely>/', views.return_model, name="return_model"),
	path('history/<str:ident_cely>/', views.model_history, name="documents_history"),

	# API
	path('download_file/<int:pk>/', views.download_file, name='download_file'),  # id of the file
]

webamcr/webamcr/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from . import views
from documents.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('', views.home, name='home'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
	path('documents/', include('documents.urls')),
    path('pas/', include('detectors.urls')),
    path('django-rq/', include('django_rq.urls')),
    path('admin/', admin.site.urls),
    path('file/delete/<int:fileId>/', views.delete, name='delete_file'),
    path('user/', include('amcrusers.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

handler403 = 'webamcr.views.err_sid'

urlpatterns += staticfiles_urlpatterns()

webamcr/documents/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.db.models import Q
from django.db import IntegrityError
from django.utils import translation

from . import xmlrpc
from . import helper
from .constants import AmcrConstants as c
from .decorators import login_required, min_user_group, permissions_required
from .forms import (FindingDocumentForm, AddNameForm, ChooseForm, CreateForm, LoginForm, EditAuthorForm)
from .models import (HeslarObjektDruh, HeslarPredmetDruh, HeslarTypNalezu, Dokument, HistorieDokumentu,
                     KomponentaDokument, HeslarObdobiDruha, HeslarArealDruha, NalezDokument, UserStorage,
                     ExtraData, JednotkaDokument, HeslarZeme, HeslarSpecifikaceObjektuDruha, HeslarSpecifikacePredmetu)
from detectors.models import HeslarJmena
from detectors.forms import ReturnFindingForm
from webamcr.views import heslar_organizace
from detectors.amcemails import email_send_3D1, email_send_3D2

import logging
import ftplib
import mimetypes
from datetime import datetime
from shapely import wkb


logger = logging.getLogger(__name__)

PREDMET_OPTION = 2
OBJEKT_OPTION = 1


@login_required
def upload_file(request, pk, **kwargs):

    context = {}
    sid = request.COOKIES.get('sessionId')
    dokument = Dokument.objects.get(pk=pk)
    context['ident_cely'] = dokument.ident_cely
    context['documentId'] = pk

    if request.method == 'POST' and request.FILES['myFile']:
        uploadedFile = request.FILES['myFile']

        try:
            xmlrpc.uploadDocumentFile(sid, dokument, uploadedFile)
            messages.add_message(request, messages.SUCCESS, c.FILE_UPLOADED_SUCCESSFULLY)
        except Exception as ex:
            logger.debug('Chyba pri uploadu souboru: ' + str(ex))
            messages.add_message(request, messages.WARNING, c.FILE_COULD_NOT_BE_UPLOADED)

        response = redirect('/documents/create/' + dokument.ident_cely)
    else:
        response = render(request, 'documents/uploadFile.html', {'context': context})

    return response


@login_required
def download_file(request, pk, **kwargs):

    sid = request.COOKIES.get('sessionId')
    try:
        name, f = xmlrpc.downloadFile(sid, pk)
        content_type = mimetypes.guess_type(name)[0]  # Use mimetypes to get file type
        f.seek(0)
        data = f.read()
        response = HttpResponse(data, content_type=content_type)
        response['Content-Length'] = str(len(data))
        response['Content-Disposition'] = "attachment; filename=%s" % name
        f.close()
    except (ftplib.all_errors, Exception):
        logger.debug('Chyba pri stahovani souboru')
        messages.add_message(request, messages.WARNING, c.FILE_COULD_NOT_BE_DOWNLOADED)
    else:
        return response


@login_required
def finding_update(request, pk, **kwargs):

    context = {}
    nalez = get_object_or_404(NalezDokument, pk=pk)
    ident_cely_dokument = nalez.komponenta_dokument.jednotka_dokument.dokument.ident_cely
    context['ident_cely'] = ident_cely_dokument
    context['detail'] = True

    if request.method == 'POST':
        form = FindingDocumentForm(request.POST)
        if form.is_valid():
            typ_nalezu_id = form.cleaned_data['typ_nalezu']
            druh_objektu_id = form.cleaned_data['druh_objektu']
            druh_predmetu_id = form.cleaned_data['druh_predmetu']
            specifikace_objektu_id = form.cleaned_data['specifikace_objektu']
            specifikace_predmetu_id = form.cleaned_data['specifikace_predmetu']
            poznamka = form.cleaned_data['poznamka']
            pocet = form.cleaned_data['pocet']

            if typ_nalezu_id:
                nalez.typ_nalezu = HeslarTypNalezu.objects.get(pk=typ_nalezu_id)
            if typ_nalezu_id == str(PREDMET_OPTION):
                nalez.druh_nalezu = druh_predmetu_id
                nalez.specifikace = specifikace_predmetu_id
            elif typ_nalezu_id == str(OBJEKT_OPTION):
                nalez.druh_nalezu = druh_objektu_id
                nalez.specifikace = specifikace_objektu_id
            else:
                logger.debug("Neznamy typ nelezu: " + str(typ_nalezu_id) + " <> " +
                             str(PREDMET_OPTION) + "/" + str(OBJEKT_OPTION))

            nalez.poznamka = poznamka
            nalez.pocet = pocet
            nalez.save()

            response = redirect('/documents/create/' + nalez.komponenta_dokument.jednotka_dokument.dokument.ident_cely)

        else:
            logger.debug("Form is not valid")
            logger.debug(form.errors)
            messages.add_message(request, messages.WARNING, c.FORM_IS_NOT_VALID)
    else:

        form_data = {
            'typ_nalezu': nalez.typ_nalezu.id,
            'poznamka': nalez.poznamka,
            'pocet': nalez.pocet,
        }
        if nalez.typ_nalezu.id == PREDMET_OPTION:
            form_data['druh_predmetu'] = nalez.druh_nalezu
            form_data['specifikace_predmetu'] = nalez.specifikace
        else:
            form_data['druh_objektu'] = nalez.druh_nalezu
            form_data['specifikace_objektu'] = nalez.specifikace

        form = FindingDocumentForm(initial=form_data)

        response = render(request, 'documents/finding.html', {
            'form': form,
            'context': context,
        })

    return response


@login_required
def finding_create(request, ident_cely, **kwargs):

    context = {}
    komponenta = get_object_or_404(KomponentaDokument, ident_cely=ident_cely)
    ident_cely_dokument = komponenta.jednotka_dokument.dokument.ident_cely
    context['ident_cely'] = ident_cely_dokument

    if request.method == 'POST':
        form = FindingDocumentForm(request.POST)
        if form.is_valid():
            typ_nalezu_id = form.cleaned_data['typ_nalezu']
            druh_objektu_id = form.cleaned_data['druh_objektu']
            druh_predmetu_id = form.cleaned_data['druh_predmetu']
            specifikace_objektu_id = form.cleaned_data['specifikace_objektu']
            specifikace_predmetu_id = form.cleaned_data['specifikace_predmetu']
            poznamka = form.cleaned_data['poznamka']
            pocet = form.cleaned_data['pocet']

            nalez = NalezDokument()

            if typ_nalezu_id:
                nalez.typ_nalezu = HeslarTypNalezu.objects.get(pk=typ_nalezu_id)
            if typ_nalezu_id == str(PREDMET_OPTION):
                nalez.druh_nalezu = druh_predmetu_id
                if specifikace_predmetu_id:
                    nalez.specifikace = specifikace_predmetu_id
            elif typ_nalezu_id == str(OBJEKT_OPTION):
                nalez.druh_nalezu = druh_objektu_id
                if specifikace_objektu_id:
                    nalez.specifikace = specifikace_objektu_id

            nalez.komponenta_dokument = komponenta
            nalez.poznamka = poznamka
            nalez.pocet = pocet
            nalez.save()
            logger.debug("Created finding: " + str(nalez.__dict__))
            messages.add_message(request, messages.SUCCESS, c.OBJECT_CREATED_SUCCESSFULLY)

            # redirect to create document
            response = redirect('/documents/create/' + ident_cely_dokument)

        else:
            logger.debug("Form is not valid")
            logger.debug(form.errors)
            messages.add_message(request, messages.WARNING, c.FORM_IS_NOT_VALID)
    else:

        form = FindingDocumentForm()
        response = render(request, 'documents/finding.html', {
            'form': form,
            'context': context,
        })

    return response

# user is admin


@login_required
def finding_delete(request, pk, **kwargs):

    nalez = NalezDokument.objects.get(pk=pk)
    ident_cely_dokument = nalez.komponenta_dokument.jednotka_dokument.dokument.ident_cely
    deleted = nalez.delete()

    if(deleted[0] > 0):
        logger.debug("Deleted finding object with id: " + str(pk) + ", " + str(deleted))
        messages.add_message(request, messages.SUCCESS, c.OBJECT_DELETED_SUCCESSFULLY)
    else:
        logger.debug("Could not find document finding object with id " + str(pk))
        messages.add_message(request, messages.WARNING, c.OBEJCT_COULD_NOT_BE_DELETED)

    return redirect('/documents/create/' + ident_cely_dokument)


@login_required
def name_create(request, **kwargs):

    if request.method == 'POST':
        form = AddNameForm(request.POST)
        if form.is_valid():

            jmena = form.cleaned_data['jmeno']
            prijmeni = form.cleaned_data['prijmeni']

            vypis = prijmeni + ','
            for j in jmena.split():
                vypis += ' ' + j.strip()[0].upper() + '.'

            try:
                jmeno = HeslarJmena(
                    jmeno=' '.join(jmena.split()),
                    prijmeni=prijmeni,
                    validated=True,
                    vypis=vypis,
                    vypis_cely=prijmeni + ', ' + jmena
                )
                jmeno.save()

                logger.debug("Nove jmeno pridano do heslare: " + jmeno.vypis)
                # Add message to the user
                messages.add_message(request, messages.SUCCESS, c.NAME_ADDED_TO_THE_LIST)
            except IntegrityError as ex:
                logger.debug(str(ex))
                messages.add_message(request, messages.WARNING, c.NAME_ALREADY_EXISTS)

            # redirect to the author edit form
            response = redirect(request.META['HTTP_REFERER'])
        else:
            logger.debug("Form is not valid.")
            logger.debug(form.errors)
            messages.add_message(request, messages.WARNING, c.FORM_IS_NOT_VALID)
    else:
        response = JsonResponse(-1, safe=False)

    return response


@login_required
def author_edit(request, ident_cely, **kwargs):

    MAX_AUTHOR_COUNT = 10
    sid = request.COOKIES.get('sessionId')
    addNameForm = AddNameForm()

webamcr/documents/templates/documents/author-edit.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}
{% block content %}
<script>
    $('.menu_library').addClass('active')
    $('.menu_create_3d').addClass('active')
</script>
<!-- page title area start -->
<div class="page-title-area title-doc mb-3">
    <div class="row align-items-center">
        <div class="col-sm-12">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title d-block d-sm-block d-md-block d-lg-none">{{LIBRARY_3D}}</h4>
                <h4 class="page-title pull-left d-none d-lg-block">{{LIBRARY_3D}}</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/" class="main-modul-doc">{{MAIN_MENU}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
                    <li><a href="/documents" class="main-modul-doc">{{LIBRARY_3D}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
                    <li><a href="/documents/create" class="main-modul-doc">{{CREATE_ENTRY}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
                    <li><a href="{% url 'documents:detail' ident_cely %}" class="main-modul-doc">{{ident_cely}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left">
                    <li class="main-modul-doc">{% trans "Autoři" %}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content-inner mb-5">
    <div class="form-row">
        <div class="col-12 col-md-11 col-xl-6">
            <p class="h2 font-weight-light card-heading ml-0">{% trans "Autoři dokumentu" %} {{ident_cely}}</p>
            <form method="post" autocomplete="off">
                {% csrf_token %}
                <div class="card create-card m-0">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group" id="autor1div">
                                    <label for="author1">{{ editAuthorForm.author1.label }}</label>
                                    {% render_field editAuthorForm.author1 id="author1" class="form-control form-control-sm selectpicker prvni" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor2div">
                                    <label for="author2">{{ editAuthorForm.author2.label }}</label>
                                    {% render_field editAuthorForm.author2 id="author2" class="form-control form-control-sm selectpicker druhy" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor3div">
                                    <label for="author3">{{ editAuthorForm.author3.label }}</label>
                                    {% render_field editAuthorForm.author3 id="author3" class="form-control form-control-sm selectpicker treti" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor4div">
                                    <label for="author4">{{ editAuthorForm.author4.label }}</label>
                                    {% render_field editAuthorForm.author4 id="author4" class="form-control form-control-sm selectpicker ctvrty" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor5div">
                                    <label for="author5">{{ editAuthorForm.author5.label }}</label>
                                    {% render_field editAuthorForm.author5 id="author5" class="form-control form-control-sm selectpicker paty" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor6div">
                                    <label for="author6">{{ editAuthorForm.author6.label }}</label>
                                    {% render_field editAuthorForm.author6 id="author6" class="form-control form-control-sm selectpicker sesty" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor7div">
                                    <label for="author7">{{ editAuthorForm.author7.label }}</label>
                                    {% render_field editAuthorForm.author7 id="author7" class="form-control form-control-sm selectpicker sedmy" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor8div">
                                    <label for="author8">{{ editAuthorForm.author8.label }}</label>
                                    {% render_field editAuthorForm.author8 id="author8" class="form-control form-control-sm selectpicker osmy" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor9div">
                                    <label for="author9">{{ editAuthorForm.author9.label }}</label>
                                    {% render_field editAuthorForm.author9 id="author9" class="form-control form-control-sm selectpicker devaty" data-live-search="true"%}
                                </div>
                                <div class="form-group" id="autor10div">
                                    <label for="author10">{{ editAuthorForm.author10.label }}</label>
                                    {% render_field editAuthorForm.author10 id="author10" class="form-control form-control-sm selectpicker desaty" data-live-search="true"%}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-2 mt-sm-0 ">
                        <a class="btn btn-amcr-3d btn-block" href="{% url 'documents:detail' ident_cely %}">{% trans "Zpět" %}</a>
                    </div>
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-2 mt-sm-2 mt-md-0 ">
                        <button type="button" class="btn btn-amcr-3d btn-block" data-toggle="modal"
                            data-target="#new_author">{% trans "Nové jméno" %}</a>
                    </div>
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-2 mt-sm-0 ">
                        <button type="submit" class="btn btn-amcr-3d btn-block">{% trans "Uložit" %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Add new author MODAL -->
    <div class="modal fade" id="new_author" tabindex="-1" role="dialog" aria-labelledby="new_authorTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="new_authorTitle">{% trans "Přidání nového autora" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" autocomplete="off" action="{% url 'documents:create_name' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="jmeno">{{ addNameForm.jmeno.label }}</label>
                                    {% render_field addNameForm.jmeno class="form-control form-control-sm" id="jmeno"   %}
                                </div>
                                <div class="form-group">
                                    <label for="prijmeni">{{ addNameForm.prijmeni.label }}</label>
                                    {% render_field addNameForm.prijmeni class="form-control form-control-sm" id="prijmeni"  %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary display-block"
                            data-dismiss="modal">{% trans "Zrušit" %}</button>
                        <button type="submit" class="btn btn-amcr-3d display-block">{% trans "Přidat Autora" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

webamcr/documents/templates/documents/file_table.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<table id="file_table" data-locale="{{ LANGUAGE_CODE }}" data-toggle="table" data-mobile-responsive="true" class="table table-hover table-borderless table-amcr file-table">
    <!--Table head-->
    <thead scope="col" id="uploads_table" class="col-documents-head">
        <tr>
            <th data-field="nazev" class="table-short" data-sortable="true">{% trans "Název" %}</th>
            <th data-field="typ" class="table-short" data-sortable="true">{% trans "Typ" %}</th>
            <th data-field="velikost" class="table-short" data-sortable="true" data-halign="left" data-align="right">{% trans "Velikost" %}</th>
            <th data-field="dautm_vytovreni" class="table-long" data-sortable="true">{% trans "Datum vytvoření" %}</th>
            <th data-field="stahnout" data-halign="left" data-align="center">{% trans "Stáhnout" %}</th>
            <th data-field="smazat" data-halign="left" data-align="center">{% trans "Smazat" %}</th>
        </tr>
    </thead>
    <!--Table head-->
    <!--Table body-->
    <tbody>
        {% for row in context.soubory %}
        <tr>
            <td>{{row.nazev}}</td>
            <td>{{row.mimetype}}</td>
            <td>{{row.size_bytes}}</td>
            <td>{{row.vytvoreno}}</td>
            <td><a class="icon-container" href="{% url 'documents:download_file' row.id %}"><i class="ti-save"></i></a>
            </td>

            <td>
                {% if context.canEdit or canEdit or canArchive or canConfirm %}
                <a class="icon-container checkchanges" data-toggle="modal" data-target="#delete_photo-{{row.id}}"><i
                        class="ti-close"></i></a>
                {% else %}
                <i class="ti-close icon-disabled"></i>
                {% endif %}
            </td>

            <!-- MODAL DELETE PHOTO -->
            <div class="modal fade" id="delete_photo-{{row.id}}" tabindex="-1" role="dialog"
                aria-labelledby="deletePhotoTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deletePhotoTitle">{% trans "Smazat fotografii" %}</h5>
                            <button type="button" class="close" aria-label="Close" data-dismiss="modal">
                                <span aria-hidden="true">&times;</span>
                        </div>
                        <div class="modal-body">
                            <p>{% trans "Opravdu chcete tuto fotografii smazat?" %}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary btn-block"
                                data-dismiss="modal">{% trans "Ne" %}</button>
                            <a class="btn btn-secondary btn-block"
                                href="{% url 'delete_file' row.id %}">{% trans "Ano" %}</a>

                        </div>
                    </div>
                </div>
            </div>
            <!-- END OF MODAL DELETE PHOTO-->
        </tr>
        <!-- End of modal - delete photo -->
        {% endfor %}
    </tbody>
    <!--Table body-->
</table>

webamcr/documents/templates/documents/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<script>
    $('.menu_library').addClass('active')
    $('.menu_home_3d').addClass('active')
</script>
<!-- page title area start -->
<div class="page-title-area title-doc mb-3">
    <div class="row align-items-center">
        <div class="col-sm-12">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title d-block d-sm-block d-md-block d-lg-none">{{LIBRARY_3D}}</h4>
                <h4 class="page-title pull-left d-none d-lg-block">{{LIBRARY_3D}}</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/" class="main-modul-doc">{{MAIN_MENU}}</a></li>
                </ul>
                <ul class="breadcrumbs pull-left" id="breadcrumbs_index">
                    <li><a href="" class="main-modul-doc">{{LIBRARY_3D}}</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content-inner mr-2 ml-2 mb-5">
    <!-- Main menu CARD area start -->
    <div class="row mt-4 mb-5">
        <div class="owl-carousel owl-theme">
            <div class="amcr-card cardhover create-doc">
                <a href="{% url 'documents:create' %}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-knihovna-3d.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{CREATE_ENTRY}}</h2>
                        </div>
                    </div>
                </a>
            </div>

            <div class="amcr-card cardhover my-doc">
                <a href="{% url 'documents:my_models'%}">
                    <div class="card">
                        <img class="card-amcr-logo img-responsive amcr-overlay"
                            src="{% static "loga/hover_logo.svg" %}">
                        <img class="card-img-top img-responsive" src="{% static "loga/AMCR-brick-knihovna-3d.png" %}"
                            alt="amcr_brick">
                        <div class="card-body">
                            <h2 class="card-text display-4 font-weight-light text-center">{{MY_MODELS}}</h2>
                        </div>
                    </div>
                </a>
            </div>
            {% if 'Správce 3D' in userDetail.role_opravneni.opravneni %}
            <div class="amcr-card cardhover choose-doc">
                    <a href="{% url 'documents:choose' %}">
                        <div class="card">
                            <img class="card-amcr-logo img-responsive amcr-overlay"
                                src="{% static "loga/hover_logo.svg" %}">
                            <img class="card-img-top img-responsive"
                                src="{% static "loga/AMCR-brick-knihovna-3d.png" %}" alt="amcr_brick">
                            <div class="card-body">
                                <h2 class="card-text display-4 font-weight-light text-center">{{CHOOSE_ENTRY}}</h2>
                            </div>
                        </div>
                </a>
            </div>
            {% endif %}
            {% if 'Správce 3D' in userDetail.role_opravneni.opravneni %}
            <div class="amcr-card cardhover manage-doc">
                    <a href="{% url 'documents:manage_models'%}">
                        <div class="card">
                            <img class="card-amcr-logo img-responsive amcr-overlay"
                                src="{% static "loga/hover_logo.svg" %}">
                            <img class="card-img-top img-responsive"
                                src="{% static "loga/AMCR-brick-knihovna-3d.png" %}" alt="amcr_brick">
                            <div class="card-body">
                                <h2 class="card-text display-4 font-weight-light text-center">{{MANAGE_DOC}}</h2>
                            </div>
                        </div>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- Texts related to cards -->
    <div class="card-text-wrapper text-justify col-12 col-md-11">
        <!-- Create detector text -->
        <div class="create-doc d-none">
            <p><strong>{% trans "AMČR - Knihovna 3D - Zapsat" %}</strong></p>
            <hr>
            <p>{% trans "Slouží k zápisu nového modelu. Zápis může provést každý registrovaný uživatel. K modelu je třeba přiložit jeho náhled, popisné údaje a v relevantních případech také prostorovou lokalizaci." %}</strong>
            </p>
        </div>
        <!-- My detector text -->
        <div class="my-doc d-none">
            <p><strong>{% trans "AMČR - Knihovna 3D - Moje" %}</strong></p>
            <hr>
            <p>{% trans "Nabídka zobrazí seznam vámi vložených modelů." %}
            </p>
        </div>
        <!-- Choose detector text -->
        <div class="choose-doc d-none">
            <p><strong>{% trans "AMČR - Knihovna 3D - Vybrat" %}</strong></p>
            <hr>
            <p>{% trans "Slouží k výběru modelů podle zadaných kritérií. K celkovému procházení a prohledávání všech archivovaných modelů slouží aplikace Digitální archiv AMČR (https://digiarchiv.aiscr.cz/)." %}
            </p>
        </div>
        <!-- Coop detector text -->
        <div class="manage-doc d-none">
            <p><strong>{% trans "AMČR - Knihovna 3D - Spravovat" %}</strong></p>
            <hr>
            <p>{% trans "Seznam modelů vložených badateli a čekajících na archivaci." %}
            </p>
        </div>
    </div>
    {% endblock %}
    {% block script %}
    <script>
        $(document).ready(function () {
            //cards - text on hover
            card_text();
            //slider init
            create_slider();
        })
    </script>
    {% endblock %}